{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7967ff18",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 필요한 라이브러리 가져오기\n",
    "from flask import Flask, render_template_string, request\n",
    "\n",
    "# Flask 애플리케이션 초기화\n",
    "app = Flask(__name__)\n",
    "\n",
    "# 질문과 선택지를 정의\n",
    "questions = [\n",
    "    {\n",
    "        \"question\": \"당신이 더 좋아하는 색깔은 무엇입니까?\",\n",
    "        \"options\": [\"빨강\", \"파랑\", \"초록\", \"노랑\"]\n",
    "    },\n",
    "    {\n",
    "        \"question\": \"당신이 더 좋아하는 동물은 무엇입니까?\",\n",
    "        \"options\": [\"강아지\", \"고양이\", \"토끼\", \"새\"]\n",
    "    }\n",
    "]\n",
    "\n",
    "# 심리 테스트 결과를 계산하는 함수\n",
    "def calculate_result(answers):\n",
    "    # 예시로 각 답변의 첫 글자를 합쳐서 결과로 반환\n",
    "    result = \"\".join([answer[0] for answer in answers])\n",
    "    return f\"당신의 심리 테스트 결과는: {result}입니다.\"\n",
    "\n",
    "# 루트 경로에 대한 라우팅\n",
    "@app.route(\"/\", methods=[\"GET\", \"POST\"])\n",
    "def home():\n",
    "    if request.method == \"POST\":\n",
    "        # 사용자가 제출한 답변 받기\n",
    "        answers = [request.form[f\"q{i}\"] for i in range(len(questions))]\n",
    "        result = calculate_result(answers)\n",
    "        return render_template_string(result_template, result=result)\n",
    "    \n",
    "    return render_template_string(form_template, questions=questions)\n",
    "\n",
    "# HTML 폼 템플릿\n",
    "form_template = \"\"\"\n",
    "<!doctype html>\n",
    "<html>\n",
    "    <head>\n",
    "        <title>심리 테스트</title>\n",
    "        <style>\n",
    "            body {\n",
    "                font-family: Arial, sans-serif;\n",
    "                background-color: #f0f8ff;\n",
    "                color: #333;\n",
    "                margin: 0;\n",
    "                padding: 0;\n",
    "                display: flex;\n",
    "                justify-content: center;\n",
    "                align-items: center;\n",
    "                height: 100vh;\n",
    "            }\n",
    "            .container {\n",
    "                background: #fff;\n",
    "                padding: 20px 40px;\n",
    "                border-radius: 8px;\n",
    "                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n",
    "                max-width: 500px;\n",
    "                width: 100%;\n",
    "            }\n",
    "            h1 {\n",
    "                font-size: 24px;\n",
    "                margin-bottom: 20px;\n",
    "                text-align: center;\n",
    "                color: #007BFF;\n",
    "            }\n",
    "            p {\n",
    "                font-size: 18px;\n",
    "                margin: 10px 0;\n",
    "            }\n",
    "            input[type=\"radio\"] {\n",
    "                margin-right: 10px;\n",
    "            }\n",
    "            input[type=\"submit\"] {\n",
    "                background-color: #007BFF;\n",
    "                color: white;\n",
    "                border: none;\n",
    "                padding: 10px 20px;\n",
    "                border-radius: 5px;\n",
    "                cursor: pointer;\n",
    "                font-size: 16px;\n",
    "                display: block;\n",
    "                margin: 20px auto 0;\n",
    "            }\n",
    "            input[type=\"submit\"]:hover {\n",
    "                background-color: #0056b3;\n",
    "            }\n",
    "        </style>\n",
    "    </head>\n",
    "    <body>\n",
    "        <div class=\"container\">\n",
    "            <h1>심리 테스트</h1>\n",
    "            <form method=\"POST\">\n",
    "                {% for i, q in enumerate(questions) %}\n",
    "                    <p>{{ q.question }}</p>\n",
    "                    {% for option in q.options %}\n",
    "                        <label>\n",
    "                            <input type=\"radio\" name=\"q{{ i }}\" value=\"{{ option }}\" required> {{ option }}\n",
    "                        </label><br>\n",
    "                    {% endfor %}\n",
    "                {% endfor %}\n",
    "                <input type=\"submit\" value=\"제출\">\n",
    "            </form>\n",
    "        </div>\n",
    "    </body>\n",
    "</html>\n",
    "\"\"\"\n",
    "\n",
    "# 결과 템플릿\n",
    "result_template = \"\"\"\n",
    "<!doctype html>\n",
    "<html>\n",
    "    <head>\n",
    "        <title>심리 테스트 결과</title>\n",
    "        <style>\n",
    "            body {\n",
    "                font-family: Arial, sans-serif;\n",
    "                background-color: #f0f8ff;\n",
    "                color: #333;\n",
    "                margin: 0;\n",
    "                padding: 0;\n",
    "                display: flex;\n",
    "                justify-content: center;\n",
    "                align-items: center;\n",
    "                height: 100vh;\n",
    "            }\n",
    "            .container {\n",
    "                background: #fff;\n",
    "                padding: 20px 40px;\n",
    "                border-radius: 8px;\n",
    "                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n",
    "                max-width: 500px;\n",
    "                width: 100%;\n",
    "                text-align: center;\n",
    "            }\n",
    "            h1 {\n",
    "                font-size: 24px;\n",
    "                margin-bottom: 20px;\n",
    "                color: #007BFF;\n",
    "            }\n",
    "            a {\n",
    "                color: #007BFF;\n",
    "                text-decoration: none;\n",
    "                font-size: 16px;\n",
    "            }\n",
    "            a:hover {\n",
    "                text-decoration: underline;\n",
    "            }\n",
    "        </style>\n",
    "    </head>\n",
    "    <body>\n",
    "        <div class=\"container\">\n",
    "            <h1>{{ result }}</h1>\n",
    "            <a href=\"/\">다시 테스트하기</a>\n",
    "        </div>\n",
    "    </body>\n",
    "</html>\n",
    "\"\"\"\n",
    "\n",
    "# Flask 애플리케이션 실행\n",
    "if __name__ == \"__main__\":\n",
    "    app.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5dbc665c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
